"""Shared configuration contracts for Reactive training."""

REACTIVE_CAMERA_IMAGE_SIZE = 512
REACTIVE_FRONT_CAMERA_INDEX = 0
REACTIVE_FRONT_CAMERA_IMAGE_SIZE = 1024
REACTIVE_BEVFORMER_FRAME_OFFSETS = tuple(range(-7, 1))
REACTIVE_BEVFORMER_HISTORY_FRAMES = 7
REACTIVE_BEVFORMER_FRAME_INTERVAL_US = 500_000
BEV_CHECKPOINT_QUALITY_GUARD_VERSION = "bev_checkpoint_quality_guard_v1"
BEV_CHECKPOINT_MIN_CLASS_IOU = 0.10
BEV_CHECKPOINT_MIN_CLASS_PRECISION = 0.15
